--
-- GENERATED BY MATUGEN — do not edit.
-- Source: matugen/templates/colors.lua
-- Regenerate: matugen image <wallpaper>
--
-- Consumed by conf/theme.lua, which falls back to a builtin palette
-- when this file is absent.
--
return {
  bg       = "111318",
  surface  = "1d2024",
  fg       = "e2e2e9",
  muted    = "8e9099",
  accent   = "a9c7ff",
  accent_2 = "dcbce1",
  urgent   = "ffb4ab",
  ok       = "bdc7dc",
}
