--
-- Colour source of truth.
--
-- `conf/colors.lua` is GENERATED by matugen from the current wallpaper
-- and is intentionally not committed. When it is absent (fresh clone,
-- matugen not yet run) we fall back to the palette below so the config
-- always loads standalone.
--
local M = {
  -- fallback palette: neutral dark, used only until matugen runs
  bg        = "1e1e2e",
  surface   = "313244",
  fg        = "cdd6f4",
  muted     = "6c7086",
  accent    = "89b4fa",
  accent_2  = "cba6f7",
  urgent    = "f38ba8",
  ok        = "a6e3a1",
}

local ok, generated = pcall(require, "conf.colors")
if ok and type(generated) == "table" then
  for k, v in pairs(generated) do M[k] = v end
  M.generated = true
else
  M.generated = false
end

-- helpers: Hyprland wants rgba(rrggbbaa) / rgb(rrggbb)
function M.rgba(hex, alpha)
  return ("rgba(%s%s)"):format(hex, alpha or "ff")
end

function M.rgb(hex)
  return ("rgb(%s)"):format(hex)
end

return M
