--
-- GENERATED BY MATUGEN — do not edit.
-- Source: matugen/templates/colors.lua
-- Regenerate: matugen image <wallpaper>
--
-- Consumed by conf/theme.lua, which falls back to a builtin palette
-- when this file is absent.
--
return {
  bg       = "{{colors.surface.default.hex_stripped}}",
  surface  = "{{colors.surface_container.default.hex_stripped}}",
  fg       = "{{colors.on_surface.default.hex_stripped}}",
  muted    = "{{colors.outline.default.hex_stripped}}",
  accent   = "{{colors.primary.default.hex_stripped}}",
  accent_2 = "{{colors.tertiary.default.hex_stripped}}",
  urgent   = "{{colors.error.default.hex_stripped}}",
  ok       = "{{colors.secondary.default.hex_stripped}}",
}
